server:
  port: 8082

spring:
  application:
    name: account-service
  profiles:
    active: dev
  cloud:
    nacos:
      server-addr: localhost:8848
      discovery:
        server-addr: ${spring.cloud.nacos.server-addr}
        username: nacos
        password: nacos

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://localhost:3306/account?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&useSSL=false&zeroDateTimeBehavior=convertToNull&serverTimezone=Asia/Shanghai
    username: gientest
    password: SecretPassword@123
  redis:
    host: localhost
    port: 6379
    password: SecretPassword@123
    database: 0
    cache:
      type: redis
      redis:
        cache-null-values: true

# rocketmq配置
rocketmq:
  nameServer: localhost:9876
  producer:
    group: my-group
    send-message-timeout: 30000

# feign配置
feign:
  client:
    config:
      feignName:
        connectTimeout: 30000
        readTimeout: 30000
  compression:
    request:
      enabled: true
      mime-types: text/xml,application/xml,application/json
      min-request-size: 2048
    response:
      enabled: true
  httpclient:
    enabled: false
    max-connections: 1000
    max-connections-per-route: 100
  hystrix:
    enabled: false
  okhttp:
    enabled: true
  sentinel:
    enabled: true


mybatis-plus:
  mapper-locations: classpath:/mapper/*Mapper.xml
  #实体扫描，多个package用逗号或者分号分隔
  typeAliasesPackage: com.central.common.model
  global-config:
    db-config:
      id-type: auto

#seata:
#  enabled: true
#  enable-auto-data-source-proxy: true #是否开启数据源自动代理,默认为true
#  tx-service-group: order-service-group  #要与配置文件中的vgroupMapping一致
#  registry: #registry根据seata服务端的registry配置
#    type: nacos #默认为file
#    nacos:
#      application: seata-server
#      server-addr: localhost:8848
#      group: "SEATA_GROUP"
#      namespace: ""
#      username: "nacos"
#      password: "nacos"
#      cluster: default # 配置自己的seata服务cluster, 默认为 default
#  config:
#    type: nacos #默认file,如果使用file不配置下面的nacos,直接配置seata.service
#    nacos:
#      server-addr: localhost:8848
#      group: "SEATA_GROUP"
#      namespace: ""
#      username: "nacos"
#      password: "nacos"
#      dataId: seataServer.properties #配置自己的dataId,由于搭建服务端时把客户端的配置也写在了seataServer.properties,所以这里用了和服务端一样的配置文件,实际客户端和服务端的配置文件分离出来更好
